# Generated by Django 2.1 on 2018-08-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patient_has_device'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='doctor',
            table='doctor',
        ),
    ]
