# Generated by Django 2.1 on 2018-08-17 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180817_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Patient'),
        ),
    ]
