# Generated by Django 2.1 on 2018-08-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180817_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readings',
            name='blood_pressure',
        ),
        migrations.AddField(
            model_name='readings',
            name='blood_pressure_Diastolic',
            field=models.CharField(max_length=3, null=True, verbose_name='Diastolic Blood Pressure'),
        ),
        migrations.AddField(
            model_name='readings',
            name='blood_pressure_Systolic',
            field=models.CharField(max_length=3, null=True, verbose_name='Systolic Blood Pressure'),
        ),
    ]
