# Generated by Django 2.1 on 2018-08-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180819_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readings',
            name='blood_pressure_Diastolic',
            field=models.CharField(max_length=3, verbose_name='Diastolic Blood Pressure'),
        ),
        migrations.AlterField(
            model_name='readings',
            name='blood_pressure_Systolic',
            field=models.CharField(max_length=3, verbose_name='Systolic Blood Pressure'),
        ),
    ]
