# Generated by Django 2.1 on 2018-08-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180819_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='last_access',
            field=models.DateTimeField(null=True, verbose_name='Last Login Time'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_access',
            field=models.DateTimeField(null=True, verbose_name='Last Login Time'),
        ),
    ]
