# Generated by Django 2.1 on 2018-09-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180819_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='degree',
            field=models.CharField(default='MBBS, MS-Neurology', max_length=300, verbose_name='Medical Degree'),
            preserve_default=False,
        ),
    ]
