# Generated by Django 2.1 on 2018-09-11 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180909_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Join Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Join Date'),
            preserve_default=False,
        ),
    ]
