# Generated by Django 2.1 on 2018-09-17 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180914_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readings',
            options={'ordering': ['-date_time', 'patient_id']},
        ),
    ]
