# Generated by Django 2.1 on 2018-09-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20180917_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readings',
            old_name='body_temparature',
            new_name='body_temperature',
        ),
    ]
