# Generated by Django 2.1 on 2018-09-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20180920_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='medical_registration_no',
            field=models.CharField(default=2001021044, max_length=100, verbose_name='Unique Permanent Registration Number'),
            preserve_default=False,
        ),
    ]
