# Generated by Django 2.1 on 2018-09-22 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_doctor_medical_registration_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='relative',
            name='age',
        ),
        migrations.AddField(
            model_name='relative',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, max_length=8, verbose_name='Date of Birth'),
            preserve_default=False,
        ),
    ]
